### PR TITLE
Modify using CAReplicatorLayer

### PR DESCRIPTION
**Pull request by dealforest**
I think that `MultiplePulsingHaloLayer` is a duplicate.
so I tried to improve it in `CAReplicatorLayer`.

I was careful to backward compatibility.

Regards best.

### CODE REVIEW

**Comment by shu223** [comment]
Thanks!!!!

**Comment by acegreen** [comment]
Are you guys going to update the master with this?

**Comment by shu223** [comment]
@acegreen Yes, already updated. Is there something wrong?

**Comment by acegreen** [comment]
No its fine. Was not updated when I posted this (I think)

**Pull request merged**
